name: finki-hub-mcp

networks:
  finki_stack:
    driver: bridge
    name: finki_stack
    # Set external to true to use an existing network
    # external: true

services:
  local-mcp:
    environment:
      CHAT_BOT_API_URL: ${CHAT_BOT_API_URL:-http://api:8880}
      DATA_STORAGE_URL: ${DATA_STORAGE_URL}
      POSTHOG_KEY: ${POSTHOG_KEY:-}
      POSTHOG_HOST: ${POSTHOG_HOST:-https://eu.i.posthog.com}
    image: ghcr.io/finki-hub/mcp-local:latest
    networks:
      - finki_stack
    ports:
      - "8808:8808"
    restart: unless-stopped
