name: Docker (Local MCP)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: finki-hub/.github/.github/workflows/docker.yaml@main
    with:
      dockerfile: ./local-mcp/Dockerfile
      context: ./local-mcp
      package-name: mcp-local
      cache-backend: registry
    secrets: inherit
